spring:
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
vielheit:
  db:
    url: jdbc:postgresql://localhost:5432/vielheit
    username: vielheit
    password: vielheit
  neo4j:
    uri: bolt://localhost:7687
    username: neo4j
    password: vielheit
  redis:
    host: localhost
    port: 6379

---
spring:
  profiles: test
vielheit:
  db:
    url: jdbc:postgresql://localhost:5432/vielheit_test

