/**
 * Application action types
 */
export type ActionType
    = 'LOGOUT'
    | 'BOOTSTRAP'
    | 'LOGIN'
    | 'LOCATION_CHANGE'
    | 'RESPONSE_ERROR'
    | 'LOGIN_START'
    | 'LOGIN_SUCCESS'
    | 'LOGIN_FAIL'
    | 'REGISTER_START'
    | 'REGISTER_SUCCESS'
    | 'REGISTER_FAIL'
    | 'EDITOR_FORM_CHANGE'
    | 'EDITOR_SUBMIT_START'
    | 'EDITOR_SUBMIT_SUCCESS'
    | 'EDITOR_SUBMIT_FAIL'
    | 'FETCH_TYPES_START'
    | 'FETCH_TYPES_SUCCESS'
    | 'FETCH_TYPES_FAIL'
    | 'EDITOR_SELECT_ITEM'
    | 'EDITOR_CHANGE_FORM'
